### ISSUE TITLE
t.map is not a function 

### ISSUE THREAD

**Issue by MOAB7698** [leizelong/translate#2]
t.map is not a function 

I have no idea about this
my file is json
````
{
    "ar":{
    "Pos_Settings": "إعدادات نقاط البيع",
    "Receipt": "الإيصال",
    "Note_to_customer": "ملاحظة للعميل",
    "Show_Note_to_customer": "إظهار ملاحظة للعميل",
    "Show_barcode": "إظهار الشفرة",
    "Show_Tax_and_Discount": "إظهار الضرائب والخصم",
    "Show_Customer": "إظهار العميل",
    "Show_Email": "إظهار البريد الإلكتروني",
    "Show_Phone": "إظهار الهاتف",
    "Show_Address": "إظهار العنوان",
    "DefaultLanguage": "اللغة الافتراضية",
    "footer": "تذييل",
    "Received_Amount": "المبلغ المستلم",
    "Paying_Amount": "مبلغ الدفع",
    "Change": "الصرف"

    }
}
````

**Comment by leizelong** [comment]
thank for you very much, report the problem. i has fixed the problem, please update plugin's version.

**Comment by leizelong** [comment]
`{
  "ar": {
    "Pos_Settings": "إعدادات نقاط البيع",
    "Receipt": "الإيصال",
    "Note_to_customer": "ملاحظة للعميل",
    "Show_Note_to_customer": "إظهار ملاحظة للعميل",
    "Show_barcode": "إظهار الشفرة",
    "Show_Tax_and_Discount": "إظهار الضرائب والخصم",
    "Show_Customer": "إظهار العميل",
    "Show_Email": "إظهار البريد الإلكتروني",
    "Show_Phone": "إظهار الهاتف",
    "Show_Address": "إظهار العنوان",
    "DefaultLanguage": "اللغة الافتراضية",
    "footer": "تذييل",
    "Received_Amount": "المبلغ المستلم",
    "Paying_Amount": "مبلغ الدفع",
    "Change": "الصرف"
  },
  "en": {
    "Pos_Settings": "Points settings settings",
    "Receipt": "Receipt",
    "Note_to_customer": "Note to the customer",
    "Show_Note_to_customer": "Show a note to the customer",
    "Show_barcode": "Show the code",
    "Show_Tax_and_Discount": "Show taxes and deduction",
    "Show_Customer": "Show the customer",
    "Show_Email": "Show the email",
    "Show_Phone": "Show the phone",
    "Show_Address": "Show the address",
    "DefaultLanguage": "Virtual language",
    "footer": "Spinning",
    "Received_Amount": "Received amount",
    "Paying_Amount": "Payment",
    "Change": "Exchange"
  }
}`

**Comment by leizelong** [comment]
![image](https://user-images.githubusercontent.com/30491515/168047010-ed920d2d-249d-4b75-ae45-88d661d1d3fe.png)


> t.map is not a function
> 
> I have no idea about this my file is json
> 
> ```
> {
>     "ar":{
>     "Pos_Settings": "إعدادات نقاط البيع",
>     "Receipt": "الإيصال",
>     "Note_to_customer": "ملاحظة للعميل",
>     "Show_Note_to_customer": "إظهار ملاحظة للعميل",
>     "Show_barcode": "إظهار الشفرة",
>     "Show_Tax_and_Discount": "إظهار الضرائب والخصم",
>     "Show_Customer": "إظهار العميل",
>     "Show_Email": "إظهار البريد الإلكتروني",
>     "Show_Phone": "إظهار الهاتف",
>     "Show_Address": "إظهار العنوان",
>     "DefaultLanguage": "اللغة الافتراضية",
>     "footer": "تذييل",
>     "Received_Amount": "المبلغ المستلم",
>     "Paying_Amount": "مبلغ الدفع",
>     "Change": "الصرف"
> 
>     }
> }
> ```
